## Important note:
## All paths defined in this configuration file must be either absolute or relative to the 
## location of the Snakefile!

## Reference annotation details
##--------------------------------------------------------------------------------------------
## Specify "Ensembl" or "Gencode" depending on your choice
annotation: Ensembl

organism: Mus_musculus # separate with underscore
build: GRCm38
release: 90
##--------------------------------------------------------------------------------------------


## Paths to existing reference files 
##--------------------------------------------------------------------------------------------
txome: /home/Shared/data/annotation/Mouse/Ensembl_GRCm38.90/cDNA_ncRNA/Mus_musculus.GRCm38.cdna.ncrna.fa.gz
genome: /home/Shared/data/annotation/Mouse/Ensembl_GRCm38.90/genome/Mus_musculus.GRCm38.dna.primary_assembly.fa
gtf: /home/Shared/data/annotation/Mouse/Ensembl_GRCm38.90/gtf/Mus_musculus.GRCm38.90.gtf
##--------------------------------------------------------------------------------------------


## Paths to indexes that will be generated by the workflow
##--------------------------------------------------------------------------------------------
salmonindex: reference/SalmonIndex/Ensembl_GRCm38.90_0.8.2
salmonk: 31
STARindex: reference/STARIndex/Ensembl_GRCm38.90.STAR.idx
##--------------------------------------------------------------------------------------------


## Information about the experiment
##--------------------------------------------------------------------------------------------
readlength: 151

## Mean and standard deviation of the fragment length distribution, for use with Salmon. 
## This is important to specify for single-end reads.
## For paired-end reads, these values will define the prior, which is then updated 
## based on the observed fragment lengths.
fldMean: 250
fldSD: 25

## Path to metadata text file. This file must contain at least the following columns:
## names: the sample identifiers = the names of the FASTQ files (excluding the _R1/R2.fastq.gz part)
## type: either SE or PE, indicating whether the sample was analyzed 
## via single-end or paired-end sequencing.
metatxt: metadata.txt

## Variables used for model fitting
## design: design formula for use with edgeR, camera and DRIMSeq. Must be a string 
## of the form "~ <predictors>"
## contrast: (comma-separated if multiple) list of contrasts to estimate in edgeR_dge.Rmd
design: "~ 0 + group"
contrast: groupH.KI.1_mo-groupH.WT.1_mo,groupSNS.KI.1_mo-groupSNS.WT.1_mo,groupH.KI.6_mo-groupH.WT.6_mo,groupSNS.KI.6_mo-groupSNS.WT.6_mo,groupH.WT.6_mo-groupH.WT.1_mo,groupH.KI.6_mo-groupH.KI.1_mo,groupSNS.WT.6_mo-groupSNS.WT.1_mo,groupSNS.KI.6_mo-groupSNS.KI.1_mo,groupSNS.WT.1_mo-groupH.WT.1_mo,groupSNS.KI.1_mo-groupH.KI.1_mo,groupSNS.WT.6_mo-groupH.WT.6_mo,groupSNS.KI.6_mo-groupH.KI.6_mo

## Gene sets used for gene set analysis with camera
## Comma-separated list of gene set categories to test with camera. 
## Must be a subset of H,C1,C2,C3,C4,C5,C6,C7
## Only required if variable "run_camera: is True (see below).
genesets: H,C5

## The maximal number of cores to use for FastQC, STAR, Salmon and DRIMSeq.
## Note that the actual number of cores available to Snakemake is determined by
## the --cores argument when it is invoked.
ncores: 20
##---------------------------------------------------------------------------------------------


## Path to a folder containing gzipped fastq files, and the file suffix (typically, either fastq or fq). 
## If you have paired-end fastq files, you also need to define the extension distinguishing the two read files. 
## More precisely, ARMOR assumes that paired-end fastq files are named 
## <sample-name>_<fqext1>.<fqsuffix>.gz and <sample-name>_<fqext2>.<fqsuffix>.gz.
## Single-end fastq files are supposed to be named 
## <sample-name>.<fqsuffix>.gz.
##---------------------------------------------------------------------------------------------
FASTQ: FASTQ
fqext1: 1
fqext2: 2
fqsuffix: fastq
##---------------------------------------------------------------------------------------------


## Path to a folder that will store the output generated by the workflow. 
## Additional subfolders of this folder will be generated by the workflow. 
## To put output in the current directory, set output to ".".
##---------------------------------------------------------------------------------------------
output: /home/Shared_sherborne/data/seq/sonu_RNAseq/polyA_Aug2019/output
##---------------------------------------------------------------------------------------------

## R setup
##---------------------------------------------------------------------------------------------
## Specify "True" if R should be installed in a conda environment or "False" if you want to use 
## your own R installation (then you have to set the path to your library in the .Renviron file)
useCondaR: True
Rbin: R
##---------------------------------------------------------------------------------------------

## Conditional conda rules
##---------------------------------------------------------------------------------------------
## Should read trimming, STAR mapping, DRIMSeq analysis and gene set analysis be performed? Set
## to False if the step is not required.
run_trimming: True
run_STAR: True
run_DRIMSeq: False
run_camera: False
##---------------------------------------------------------------------------------------------
